[package]
name = "pathfinding-jni"
version = "2025.0.1"
edition = "2021"

[lib]
name = "pathfinding_jni"
path = "src/main/rust/lib.rs"
crate-type = [ "cdylib" ]

[dependencies]
arrayvec = "0.7.4"
itertools = "0.13.0"
jni = "0.21.1"
lerp = "0.5.0"
ordered-float = "4.2.1"
